;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=/Game/Blueprints/Widgets/_WidgetManager/Data/DT_UIGameplayTags.DT_UIGameplayTags
+GameplayTagTableList=/Game/Blueprints/Data_assets/Weapon_Usable/Data/DT_WeaponTypeTags.DT_WeaponTypeTags
+GameplayTagTableList=/Game/Blueprints/Data_assets/Weapon_Usable/Data/DT_WeaponUsageTypeTags.DT_WeaponUsageTypeTags
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Gameplay Atributes.CanHeal",NewTagName="Gameplay Atributes.CanBeHealed")
+GameplayTagRedirects=(OldTagName="Gameplay Atributes.Weapon",NewTagName="Gameplay Atributes.CharacterWeaponAtributes")
+GameplayTagRedirects=(OldTagName="WeaponDA.Ovewrite.Info.WeaponModel",NewTagName="WeaponDA.Ovewrite.Info.WeaponVisual")
+GameplayTagList=(Tag="EQS",DevComment="")
+GameplayTagList=(Tag="EQS.Failed",DevComment="")
+GameplayTagList=(Tag="EQS.Succeed",DevComment="")
+GameplayTagList=(Tag="Gameplay Atributes",DevComment="Used for Building objects")
+GameplayTagList=(Tag="Gameplay Atributes.Building",DevComment="Used for object building")
+GameplayTagList=(Tag="Gameplay Atributes.Can Be Cheesed",DevComment="can this object be cheesed")
+GameplayTagList=(Tag="Gameplay Atributes.CanBeHealed",DevComment="Can this object be healed by healing items for characters")
+GameplayTagList=(Tag="Gameplay Atributes.CanBeHealedCorrupted",DevComment="Can this object be Healed by corrupted enemies")
+GameplayTagList=(Tag="Gameplay Atributes.CanBeRepaired",DevComment="Can this object be repaired, used for vehicles")
+GameplayTagList=(Tag="Gameplay Atributes.CanGrabAmmo",DevComment="")
+GameplayTagList=(Tag="Gameplay Atributes.CanGrabPowerUps",DevComment="Can this character Grab Power Ups")
+GameplayTagList=(Tag="Gameplay Atributes.CharacterWeaponAtributes",DevComment="")
+GameplayTagList=(Tag="Gameplay Atributes.CharacterWeaponAtributes.CanBlock?",DevComment="Can this character use the weapon block feature if enabled?")
+GameplayTagList=(Tag="Gameplay Atributes.Controller.CanFish",DevComment="")
+GameplayTagList=(Tag="Gameplay Atributes.Executions",DevComment="Execution Atributes")
+GameplayTagList=(Tag="Gameplay Atributes.Executions.CanBeExecuted",DevComment="Can this cahracter be executed")
+GameplayTagList=(Tag="Gameplay Atributes.ExplodeOnDeath",DevComment="USed for exploding character on death")
+GameplayTagList=(Tag="Gameplay Atributes.Hostage.CanBeHostage",DevComment="Can this character be grabbed as a hostage")
+GameplayTagList=(Tag="Gameplay Atributes.Hostage.CanGrabHostage",DevComment="Can this character grab hostages")
+GameplayTagList=(Tag="Gameplay Atributes.Movement.NoCharCollision.CloseToSpawn",DevComment="Used for controlling collision")
+GameplayTagList=(Tag="Gameplay Atributes.Movement.Stuck.AIMeleeAttack",DevComment="")
+GameplayTagList=(Tag="Gameplay Atributes.Movement.Stuck.Dodge",DevComment="")
+GameplayTagList=(Tag="Gameplay Atributes.Movement.Stuck.Exploding",DevComment="Is Character exploding")
+GameplayTagList=(Tag="Gameplay Atributes.Movement.Stuck.NavLink",DevComment="Used for traversing nav link")
+GameplayTagList=(Tag="Gameplay Atributes.Movement.Stuck.NavLink.JumpSimple",DevComment="")
+GameplayTagList=(Tag="Gameplay Atributes.Ragdoll.CanRagdoll",DevComment="Can this character be ragdolled")
+GameplayTagList=(Tag="Gameplay Atributes.Water",DevComment="Used for fishing")
+GameplayTagList=(Tag="HordeTags.PowerUps.DoublePoints",DevComment="")
+GameplayTagList=(Tag="HordeTags.PowerUps.InstantKill",DevComment="")
+GameplayTagList=(Tag="HordeTags.PowerUps.MaxAmmo",DevComment="Max Ammo")
+GameplayTagList=(Tag="HordeTags.PowerUps.Nuke",DevComment="Nuke Power Up")
+GameplayTagList=(Tag="ModdingTags.CharacterTags.ForceMaterialOverwrite",DevComment="Force zombie materials to be overwritten by the base materials instead")
+GameplayTagList=(Tag="movementdone",DevComment="")
+GameplayTagList=(Tag="movementdone.Failed",DevComment="")
+GameplayTagList=(Tag="movementdone.ReachedGoal",DevComment="")
+GameplayTagList=(Tag="Mover.NullMovement",DevComment="No movement at all")
+GameplayTagList=(Tag="UI.Action.Escape",DevComment="Go Back")
+GameplayTagList=(Tag="UI.Layer.Game",DevComment="Game Layer")
+GameplayTagList=(Tag="UI.Layer.GameMenu",DevComment="Game Menus Layer")
+GameplayTagList=(Tag="UI.Layer.Menu",DevComment="Menu Layer")
+GameplayTagList=(Tag="UI.Layer.Modal",DevComment="Popup/Dialog Layer")
+GameplayTagList=(Tag="WeaponDA",DevComment="TagsForWeaponValues")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Animations.Equip",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Animations.Idle",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Animations.Inspect",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Animations.Reload",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Animations.Shoot",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.Buffs",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.Damage",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.Description",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.FireMode",DevComment="Fire Rate, Hitscan or projectile + damage values")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.FireRate",DevComment="Fire Rate")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.HoldInfo",DevComment="how the weapon is held and how it works")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.Name",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.Visual",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.Visual.AllowCasingSkins",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.Visual.AllowSkins",DevComment="")
+GameplayTagList=(Tag="WeaponDA.Ovewrite.Info.Visual.Model",DevComment="")

